default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy_lives_development
  username: wendellopes
  password: w2n1b1b2

test:
  <<: *default
  database: easy_lives_test
  username: wendellopes
  password: w2n1b1b2

production:
  <<: *default
  database: easy_lives_production
  username: easy_lives
  password: <%= ENV['EASY_LIVES_DATABASE_PASSWORD'] %>
